version: '2'
services:
  aplicacaojhipster-app:
    image: aplicacaojhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://aplicacaojhipster-mysql:3306/aplicacaojhipster?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_CACHE_MEMCACHED_SERVERS=aplicacaojhipster-memcached:11211
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  aplicacaojhipster-mysql:
    extends:
      file: mysql.yml
      service: aplicacaojhipster-mysql
  aplicacaojhipster-memcached:
    extends:
      file: memcached.yml
      service: aplicacaojhipster-memcached
